### ISSUE TITLE
Which development boards does NXP's SR150 or SR040 UWBIOT refer to？

### ISSUE THREAD

**Issue by codetang-2417** [nxp-uwb/UWBMobileKit#1]
If I want to use Android phones and SR150 based IoT devices to run through this example, which development board should I buy?
Thank you for answering

**Comment by jgeslin** [comment]
Hi,

The application is compatible with SR040 and SR150 based solution.

For SR150 Hardware, please refer tot the list [https://www.nxp.com/products/wireless/secure-ultra-wideband-uwb/trimension-sr150-secure-uwb-solution-for-iot-devices:SR150](https://www.nxp.com/products/wireless/secure-ultra-wideband-uwb/trimension-sr150-secure-uwb-solution-for-iot-devices:SR150)

For SR040, see [https://www.nxp.com/products/wireless/secure-ultra-wideband-uwb/trimension-sr040-reliable-uwb-solution-for-iot:SR040](https://www.nxp.com/products/wireless/secure-ultra-wideband-uwb/trimension-sr040-reliable-uwb-solution-for-iot:SR040)

You can also use solution from Mobile Knowledge: [https://www.themobileknowledge.com/products/](https://www.themobileknowledge.com/products/)

Regards,
Jeremy.

**Comment by codetang-2417** [comment]
Thank you！
